export const ACTION_TYPES = {
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  RESET: 'RESET'
};

export const ACTIONS_CHARACTERS = {
  GET_CHARACTERS: 'GET_CHARACTERS',
  CLEAR_CHARACTERS: 'CLEAR_CHARACTERS'
};

export const ACTIONS_COUNTRIES = {
  GET_COUNTRIES: 'GET_COUNTRIES',
  ADD_COUNTRY: 'ADD_COUNTRY',
  DELETE_COUNTRY: 'DELETE_COUNTRY'
};
