// export const INCREMENT = 'INCREMENT';
// export const DECREMENT = 'DECREMENT';
// export const RESET = 'RESET';

export const ACTION_TYPES = {
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  RESET: 'RESET'
};

export const ACTIONS_CHARACTERS = {
  GET_CHARACTERS: 'GET_CHARACTERS',
  CLEAR_CHARACTERS: 'CLEAR_CHARACTERS'
};
